language: node_js

cache:
  directories:
    - node_modules

matrix:
  include:
    - node_js: "lts/*"
      env: YARN_TASK=coverage:node
    - node_js: "node"
      env: YARN_TASK=coverage:node
    - node_js: "node"
      env: YARN_TASK=coverage:browser
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

script: yarn run lint && yarn run build && yarn run $YARN_TASK

after_success: yarn run coveralls

notifications:
  email: false
